### ISSUE TITLE
how to decrypt the .enc file?😂

### ISSUE THREAD

**Issue by lost22git** [0sumcode/0up#1]

**Comment by danhstevens** [comment]
After uploading you should be provided with a link like below:
![image](https://github.com/0sumcode/0up/assets/1061040/409fb86e-0709-4ce3-b1a3-e32312e206da)

Copy/pasting that allows you to share/view the upload. If you're not seeing that screen, let me know your browser information.

**Comment by lost22git** [comment]
> After uploading you should be provided with a link like below:
> ![image](https://github.com/0sumcode/0up/assets/1061040/409fb86e-0709-4ce3-b1a3-e32312e206da)
> 
> Copy/pasting that allows you to share/view the upload. If you're not seeing that screen, let me know your browser information.

I can see the uploaded file, but get a encrypted file when download it

**Comment by danhstevens** [comment]
Interesting. Let me know your browser / operating system and I'll see if I can recreate.

**Comment by lost22git** [comment]
> Interesting. Let me know your browser / operating system and I'll see if I can recreate.

qutebrowser and windows11

**Comment by lost22git** [comment]
> > Interesting. Let me know your browser / operating system and I'll see if I can recreate.
> 
> qutebrowser and windows11

Now I work normally, it may be an occasional incident before 😅
